services:
  dagster:
    build: dagster
    ports:
      - "3000:3000"
    environment:
      - SQLITE_STORAGE_BASE_DIR=/opt/dagster/sqlite/
      - SQLITE_DATABASE=/opt/dagster/app/persistent_db/ny_taxi.db
    volumes:
      - ./persistent_db:/opt/dagster/app/persistent_db
      - ./persistent_db/dagster/:/opt/dagster/sqlite/

  metabase:
    image: metabase/metabase
    ports:
      - "5000:3000"
    environment:
      - MB_DB_FILE=/persistent_db/metabase.db
      - MB_SETUP_ADMIN_EMAIL=fake-admin@example.com  # Dummy admin email
      - MB_SETUP_ADMIN_PASSWORD=fakepassword  # Dummy admin password
      - MB_ANON_ACCESS_ENABLED=true  # Enable anonymous access
      - MB_EMBEDS_ANON_ACCESS_TOKENS=true  # Allow anonymous access to public dashboards
    volumes:
      - ./persistent_db:/persistent_db